### ISSUE TITLE
Improve documentation of dc.load's `datasets` parameter

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/ga-datacube-env#112]
`dc.load` has a very useful parameter `datasets` that lets you feed in a (potentially filtered) list of datasets returned by `dc.find_datasets`. The parameter is documented with:

`:param datasets: Optional. If this is a non-empty list of :class: datacube.model.Dataset objects, these will be loaded instead of performing a database lookup`

However, if the user follows this instruction directly, they receive a non-informative error because a product name apparently needs to be included in the `dc.load` call for it to work:

```
datasets_list = dc.find_datasets(product = 'ls8_nbart_albers', **query)
dc.load(datasets=datasets_list[5:10])
```
```
AttributeError: 'NoneType' object has no attribute 'grid_spec'
```

i.e. this works:

```
datasets_list = dc.find_datasets(product = 'ls8_nbart_albers', **query)
dc.load(product = 'ls8_nbart_albers', datasets=datasets_list[5:10])
```

The documentation for this function could be improved by mentioning that the `datasets` parameter only works if you manually specify a product name, because currently the user has no way of knowing what is causing the error. Alternatively, the error message could be made more explicit.

**Comment by jeremyh** [comment]
We should probably make `dc.load` grab the product from the datasets themselves anyway. Otherwise users could specify a different product from the datasets they are giving. 

(simplest option: `product=datasets[0].type`, +validation)

**Comment by robbibt** [comment]
This has been fixed for a long time, closing
