### ISSUE TITLE
keras

### ISSUE THREAD

**Issue by benjimin** [GeoscienceAustralia/ga-datacube-env#117]
Can we add the machine learning library "keras" to the conda install recipe, for the dea python environment please?

(I assume this will pull in TensorFlow as a dependency. At this stage we're probably just after the CPU version, but after it is working the next thing we'll want from conda is likely to be "tensorflow-gpu".)

**Comment by santoshamohan** [comment]
`Keras` (v2.2.4) added to new `dea` module, `dea/20181015`.
