### ISSUE TITLE
Add 'rasterstats' to default DEA python modules

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/ga-datacube-env#118]
The `rasterstats` Python module (https://github.com/perrygeo/python-rasterstats) contains many very useful tools for raster + vector operations, and is currently being pip-installed by many members of the science teams.

It would be fantastic if this could be added to the default DEA python modules.
@omad @cbur24 @CEKrause

**Comment by santoshamohan** [comment]
`rasterstats` (v0.13.0) added to new `dea` module, `dea/20181015`.
