### ISSUE TITLE
Where to find the getting started document 

### ISSUE THREAD

**Issue by r-cassel** [GeoscienceAustralia/ga-datacube-env#14]
Some time ago I was emailed this Word document written by Kat Owen

I'd like to help others to get started and it would be useful to point them in the direction of the latest version of this if available.

Cheers
Bec

[AGDC Version 2 “How to” guides v0.1.docx](https://github.com/GeoscienceAustralia/digitalearthau/files/1240928/AGDC.Version.2.How.to.guides.v0.1.docx)

**Comment by andrewdhicks** [comment]
Hi Bec,

Here's our most up-to-date documentation:
http://geoscienceaustralia.github.io/digitalearthau/

It's still a work in progress, so any feedback would be welcomed!

Cheers,
Andrew

**Comment by r-cassel** [comment]
Thanks Andrew :)
