### ISSUE TITLE
Inconsistent Python Environment Variables

### ISSUE THREAD

**Issue by omad** [GeoscienceAustralia/ga-datacube-env#170]
## Problem
When using `module load dea` the `PYTHONUSERBASE` environment variable is being set to the wrong path, and doesn't match `PATH` or `PYTHONPATH`.

`PYTHONUSERBASE` is being set based on the version of `dea` module, but should be set based on the version of `dea-env` module.

## Background

It's intended that users of the DEA NCI Environment Modules be able to install extra python packages into their home directory using `pip install --user`.

In the past we have had trouble with user packages conflicting with Environment Module packages, and so when the module is loaded we change the `PYTHONUSERBASE` and `PATH` variables to point to a directory based on the Environment Module version which is loaded such as `~/.digitalearthau/20181011/local`, so that extra packages must be re-installed when a new `dea-env` module is released..

Most users load the `dea` module directly, not the `dea-env` module, and we want  `PYTHONUSERBASE` to match the version of `dea-env`, but at the moment it is being set to the version of `dea`.

**Comment by santoshamohan** [comment]
Fixed in new `dea` module, `dea/20181015`.
