### ISSUE TITLE
Add checksumdir to DEA Environment

### ISSUE THREAD

**Issue by omad** [GeoscienceAustralia/ga-datacube-env#173]
It was recently added as a dependency of `eo-datasets`. See 
https://github.com/GeoscienceAustralia/eo-datasets/commit/b44b7102cdf1a805db2d74d94a9c3a2f9913cd0b#diff-2eeaed663bd0d25b7e608891384b7298

Check whether to install from PyPI with `pip` or from condo-forge.

**Comment by santoshamohan** [comment]
`checksumdir` (v1.1.4) added to new `dea` module, `dea/20181015`.
