### ISSUE TITLE
Slow performance for Sentinel 2 when lazily loading data with Dask

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/ga-datacube-env#175]
I'm having issues with very slow performance when lazily loading Sentinel 2 using `dask`. Usually `dc.load()` with `dask_chunks` activated loads almost instantly, however Sentinel 2 data often takes several minutes to complete this step. This delay occurs before `.compute()` has been called, so is likely not related to Sentinel 2's greater data volume.

For Landsat 8, this small approximately 8 x 8 km `dc.load` with `dask_chunks` loads instantaneously: **259 ms ± 45.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each):**
```
%%timeit

import datacube

dc = datacube.Datacube(app='Dask test')

# Approx 8 x 8 km2 area
query = {'x': (955363.2405178696, 970963.2405178696),
         'y': (-3573391.872621911, -3556391.872621911),
         'time': ('2016-06-01', '2017-09-01'),
         'crs': 'EPSG:3577',
         'output_crs': 'EPSG:3577',
         'resolution': (-25, 25)}

# Lazily load Landsat 8 data using dask               
data = dc.load(product='ls8_nbart_albers', 
               measurements=['red', 'green', 'blue'],
               group_by='solar_day', 
               dask_chunks={'time': 1},
               **query)
```

The same query with Sentinel 2A is very slow: **54.9 s ± 253 ms per loop (mean ± std. dev. of 7 runs, 1 loop each):**

```
%%timeit

import datacube

dc = datacube.Datacube(app='Dask test')

# Lazily load Sentinel 2 data using dask               
data = dc.load(product='s2a_ard_granule', 
               measurements=['nbart_red', 'nbart_green', 'nbart_blue'],
               group_by='solar_day', 
               dask_chunks={'time': 1},
               **query)
```

**Comment by omad** [comment]
Looking at the database, there are several indexes on the `s2a_ard_granule` product which haven't been created properly.

I attempted to create them yesterday, but without much luck, I'll try again and keep an update here.

**Comment by robbibt** [comment]
Fairly certain this has been resolved
