### ISSUE TITLE
mpi4py package doesn't work correctly in PBS jobs

### ISSUE THREAD

**Issue by omad** [GeoscienceAustralia/ga-datacube-env#176]
The `mpi4py` package from conda-forge doesn't seem to integrate properly into the PBS system on the NCI, it's only aware of a single node, not multiple nodes.

We should either remove it, or investigate making it work correctly.

The current work around is to not use the `dea` modules, and `module use mpi4py/3.0.0` instead. It is compiled and supplied by the NCI, but only works with their `python` modules which are missing a lot of packages required by `dea`.

**Comment by santoshamohan** [comment]
Installing `openmpi/3.1.2` version of `NCI` package on top of `dea/20181015` package does work. Tested with following setup:
- Number of nodes = 31
- Number of CPU's = (31 * 16)
- Memory requested = (31 * 16 * 4)

```
#!/bin/bash
#PBS -q normal
#PBS -l walltime=20:00:00
#PBS -l ncpus=496
#PBS -l mem=1984GB
#PBS -l jobfs=10GB
#PBS -l wd
module use /g/data/v10/public/modules/modulefiles/
module load dea/20181015
module load openmpi/3.1.2
mpirun --tag-output --report-bindings python3 converter/cog_conv_app.py mpi-cog-convert -c aws_products_config.yaml --output-dir /tmp/wofls_cog/ -p wofs_albers /tmp/wofs_albers_file_list
```
Using the above PBS script it was observed that the `mpirun` program was distributed across all 31 `nodes` and > 85% job efficiency was achieved.

**Comment by santoshamohan** [comment]
`openmpi` version lesser than `3.1.2` did not work with the latest `dea` module (`dea/20181015`). The reason being, `dea` module had `openmpi/3.1.2` version packaged with it.

**Comment by omad** [comment]
Awesome work finding this out!

We should just document this and move on, I don't think we want to automatically load `openmpi` when loading the `dea-env` module...

**Comment by omad** [comment]
So, MPI solution = `module load openmpi/3.1.2`
