### ISSUE TITLE
Jupyter notebooks desktop link uses the wrong DEA module

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/ga-datacube-env#185]
The DEA user guide (http://geoscienceaustralia.github.io/digitalearthau/connect/install.html) recommends that users run the following script to create an icon on their desktop which allows them to launch Jupyter Notebooks:

`sh /g/data/v10/public/digitalearthau/install.sh`

This creates the file `g/data/v10/public/digitalearthau/dea.desktop`, which contains the following command:

```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=true
Icon[en_AU]=/g/data/v10/public/digitalearthau/dea-icon.png
Name[en_AU]=Digital Earth Australia
Comment[en_AU]=Jupyter Notebooks for Digital Earth Australia
Exec=bash -c "module use /g/data/v10/public/modules/modulefiles && module load agdc-py3-prod && jupyter notebook --notebook-dir=~ --NotebookApp.default_url=/tree/dea_examples"
Name=Digital Earth Australia
Comment=Jupyter Notebooks for Digital Earth Australia
Icon=/g/data/v10/public/digitalearthau/dea-icon.png
```

This loads a defunct version of DEA (`agdc-py3-prod`), and should be replaced with the following command that correctly loads `module load dea`:

```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=true
Icon[en_AU]=/g/data/v10/public/digitalearthau/dea-icon.png
Name[en_AU]=Digital Earth Australia
Comment[en_AU]=Jupyter Notebooks for Digital Earth Australia
Exec=bash -c "module use /g/data/v10/public/modules/modulefiles && module load dea && jupyter notebook --notebook-dir=~ --NotebookApp.default_url=/tree/dea_examples"
Name=Digital Earth Australia
Comment=Jupyter Notebooks for Digital Earth Australia
Icon=/g/data/v10/public/digitalearthau/dea-icon.png
```

**Comment by santoshamohan** [comment]
Updated `g/data/v10/public/digitalearthau/dea.desktop` config file to load default `dea` module.
When the users run `g/data/v10/public/digitalearthau/install.sh` script, `Digital Earth Australia` icon shall load default `dea` module.
