### ISSUE TITLE
Add `cmocean` to default DEA environment 

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/ga-datacube-env#196]
I'd like to propose a new DEA default module: `cmocean` contains a wide selection of geoscience-themed Matplotlib colour maps that have been optimised to :

1) Reflect real-world phenomena like intensity, depth, concentrations, turbidity, temperature
2) Be interpreted in a logical and linear way by human eyes ('perceptually uniform')
3) Be (mostly) colourblind friendly

https://matplotlib.org/cmocean/

Having easy access to best-practice data visualisation resources like `cmocean` would be very valuable for many scientific applications in DEA given that we routinely produce and visualise large spatial datasets.

@santoshamohan

**Comment by santoshamohan** [comment]
`cmocean` is now available in  `dea-env/20190329` and `dea/20190329` modules.
