### ISSUE TITLE
Attempt to make environments immutable

### ISSUE THREAD

**Issue by omad** [GeoscienceAustralia/ga-datacube-env#2]
The way the NCI environments/modules are created allows them to be modified by anyone in the `v10_w` group, simply by running a `pip install foo` or `pip install -U foo`.

Since we want these environments to be immutable, I think we should remove the `w` bit from everything after the environment has been created.

**Comment by jeremyh** [comment]
Good idea. I've run it over today's environments. I'll add it to the creation script.
