### ISSUE TITLE
Add `jupyterlab-git` to default DEA environment

### ISSUE THREAD

**Issue by santoshamohan** [GeoscienceAustralia/ga-datacube-env#214]
A JupyterLab extension for version control using git.
[jupyterlab-git](https://github.com/jupyterlab/jupyterlab-git)

**Comment by santoshamohan** [comment]
`jupyterlab-git` lab extension is added as part of [dea-orchestration: PR#121](https://github.com/GeoscienceAustralia/dea-orchestration/pull/121/files)

**Comment by robbibt** [comment]
This is now completed
