### ISSUE TITLE
Add `@jupyter-widgets/jupyterlab-manager` extension to default DEA environment

### ISSUE THREAD

**Issue by Kirill888** [GeoscienceAustralia/ga-datacube-env#215]
Jupyter lab component of ipywidgets:

https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-the-jupyterlab-extension

**Comment by santoshamohan** [comment]
`@jupyter-widgets/jupyterlab-manager` lab extension is added as part of [dea-orchestration: PR#121](https://github.com/GeoscienceAustralia/dea-orchestration/pull/121/files)

**Comment by robbibt** [comment]
This is now completed
