### ISSUE TITLE
Add nbdime extension to DEA env.

### ISSUE THREAD

**Issue by Kirill888** [GeoscienceAustralia/ga-datacube-env#216]
`nbdime` is a tool that allows you to visually diff notebook changes, very handy.

https://nbdime.readthedocs.io/en/latest/installing.html

**Comment by santoshamohan** [comment]
`nbdime` extension is added as part of [dea-orchestration: PR#121](https://github.com/GeoscienceAustralia/dea-orchestration/pull/121/files)

**Comment by robbibt** [comment]
This is now completed
