### ISSUE TITLE
Add `jupyter-leaflet` lab extension to DEA env

### ISSUE THREAD

**Issue by andrewdhicks** [GeoscienceAustralia/ga-datacube-env#220]
We currently have ipyleaflet for jupyter notebooks. It would be great to have it for jupyterlab as well!

`jupyter labextension install jupyter-leaflet`

More info at https://ipyleaflet.readthedocs.io/en/latest/installation.html
Thanks!

**Comment by santoshamohan** [comment]
`jupyter-leaflet` lab extension is added as part of [dea-orchestration: PR#121](https://github.com/GeoscienceAustralia/dea-orchestration/pull/121/files)

**Comment by robbibt** [comment]
This is now completed
