### ISSUE TITLE
Add dask-labextension to DEA env

### ISSUE THREAD

**Issue by andrewdhicks** [GeoscienceAustralia/ga-datacube-env#221]
The dask-labextension makes it easier to manage dask clusters from jupyter lab, including port forwarding of dashboards from the cluster to the browser.

Info here:
https://github.com/dask/dask-labextension

**Comment by santoshamohan** [comment]
`dask-labextension` lab extension is added as part of [dea-orchestration: PR#121](https://github.com/GeoscienceAustralia/dea-orchestration/pull/121/files)

**Comment by robbibt** [comment]
This is now completed
