### ISSUE TITLE
Add latest version of `odc.algo` to NCI environment

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/ga-datacube-env#253]
The latest version of `odc.algo` (https://github.com/opendatacube/odc-tools/tree/master/libs/algo) is required to allow us to roll out the dask-optimised version of `load_ard` here: https://github.com/GeoscienceAustralia/dea-notebooks/pull/527

We need it to be available in the default `module load dea` before we accept the PR above.

It can be installed via:

`pip install --extra-index-url="https://packages.dea.ga.gov.au" odc_algo`

**Comment by alexgleith** [comment]
This has been done, right @omad?

**Comment by omad** [comment]
Done in code but not deployed yet

**Comment by robbibt** [comment]
This is now completed
