### ISSUE TITLE
Update `geopandas` to version 0.7.0 to match DEA Sandbox

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/ga-datacube-env#256]
The current version of `geopandas` in the DEA NCI environment (`dea/unstable`) is:
```
gpd.__version__
'0.6.3'
```
Version 0.7.0 makes a major change in the way CRS objects are represented (i.e. pyproj CRS objects vs dictionaries) which will need to be addressed soon to avoid science team code from breaking. The latest version is also more compatible with datacube 1.8, which should make it easier to interest between vector objects and datacube.

Version 0.7.0 also contains some really useful new features including a new `clip` function and revised `overlay` function: https://geopandas.readthedocs.io/en/latest/changelog.html

It's also the version available on the DEA Sandbox, and it would be great to synchronise the two versions.

**Comment by omad** [comment]
Sorry, this totally missed my attention. I'm not sure why it hasn't updated in `dea/unstable` yet but I'll look now. There might be something pinning it to an old version ¯\_(ツ)_/¯

**Comment by omad** [comment]
All the upstream dependencies (including geopandas) are in the `dea-env` module, and I'd forgotten to rebuild that for a really long time.

I'm creating a new version of it now, and if successful, will redo `dea/unstable` which will point to the latest `dea-env`. Should include new versions of *lots* of things, hopefully doesn't break anything else...

**Comment by robbibt** [comment]
Awesome, thanks @omad ! I'm using `dea/unstable` pretty heavily at the moment, so will hopefully be able to pick up anything that breaks dramatically. Can you ping me when you think `dea/unstable` is ready to test?

**Comment by omad** [comment]
Update: This isn't going as smoothly as I hoped, the `dea-env` module has a _massive_ list of conda-forge and other conda packages in it, and it's having trouble resolving a set of versions that will work. I might need to trim and retry, but it's taking a long time to even say anything.

Will post when I have more news.

**Comment by robbibt** [comment]
This is now completed. Thanks @omad!
