### ISSUE TITLE
Update `module load dea` to use Datacube v1.8

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/ga-datacube-env#257]
`datacube` version 1.8 has recently been released (https://github.com/opendatacube/datacube-core/releases/tag/datacube-1.8.0). 

It would be great to have the default `module load dea` environment updated to use `datacube` version 1.8 so that we can release important updates to science team code that currently depend on version 1.8 (e.g. https://github.com/GeoscienceAustralia/dea-notebooks/pull/527), and update existing code to take advantage of new version 1.8 features.

**Comment by alexgleith** [comment]
I believe @Kirill888 has implemented this into a test module.

Can we get some details about that Kirill, so that we can get some folks to test it?

**Comment by Kirill888** [comment]
We do have a new environment on gadi ready for testing - `dea/20200526` . Some libraries had to be dropped, for now, as they conflicted with other packages.

- `pytorch`
- `rsgislib`

`pytorch` can be installed via pip though, and for `rsgislib` we have to wait until they sort out `libgeos-3.8` issues (https://github.com/conda-forge/rsgislib-feedstock/pull/31).

We are yet to test it beyond basic "smoke tests" @robbibt

**Comment by robbibt** [comment]
Nice, I'll test it out!

**Comment by robbibt** [comment]
I'm having an unexpected issue with  `module load dea/20200526`. When I launch Jupyterlab from the VDI, the Firefox window freezes and after a few seconds I get the warning below. Regardless of what I do from here, the window remains frozen and I can't interact with Jupyterlab.

![image](https://user-images.githubusercontent.com/17680388/83222570-f33c6800-a1bb-11ea-8b87-6455ef596f25.png)

This works without issues with `module load dea`.

Would anyone be able to try and reproduce this to see if it's just me? Steps to reproduce are: load Jupyterlab using:
```
module use /g/data/v10/public/modules/modulefiles
module load dea/20200526
module load otps
module load ffmpeg

cd <your notebooks directory>
jupyter lab
```
And then load a notebook e.g. `Frequently_used_code/Animated_timeseries.ipynb` and run all cells. 

(If the issue above doesn't occur, close JupyterLab without closing off the notebook tab, and then re-run the steps above. When JupyterLab launches with that notebook in the window at startup, you should see the warning above.)

**Comment by robbibt** [comment]
^ So far no-one else can reproduce this, so it seems like it's something on my end (although clearing Firefox's cache and restarting the VDI has no effect, and it still works correctly on `module load dea`). Hopefully it will magically resolve itself by next week...

**Comment by Kirill888** [comment]
it could be various jupyter{lab} config/cache folders. When I had similar problem, I was suspecting git-related extensions for some reason I no longer recall, so maybe switching to a clean checkout might help.

**Comment by robbibt** [comment]
Hi everyone,

I've just audited DEA Notebooks on the NCI using both `module load dea` and the new `module load dea/20200526`.

My overall finding is that significantly more code fails on `module load dea` than `module load dea/20200526` (more details: https://github.com/GeoscienceAustralia/dea-notebooks/issues/507#issuecomment-637940989), but these failures haven't been noticed until now. `module load dea` is very old and has some key differences in package versions (e.g. `datacube` < 1.8, `geopandas` < 0.7.0 etc), which has made it difficult to write code that works on both the Sandbox and NCI.

Rather than fix up DEA Notebooks to work on the current `module load dea`, I think it would be better to make `module load dea/20200526` the default module on the NCI whenever it's practical to do so. As the status quo is broken anyway, I think changing to the newer module would probably cause less issues with broken code in the long run.

**Comment by omad** [comment]
I'm working on updating `module load dea` now. There's already `20200602`, and I'm about to roll another (hopefully) to fix WOfS breaking in April.

**Comment by robbibt** [comment]
This is now completed
