### ISSUE TITLE
Problem importing hdstats on VDI

### ISSUE THREAD

**Issue by eloise-b** [GeoscienceAustralia/ga-datacube-env#258]
Hi folks,
I'm working in the VDI environment to do some testing, and I was trying to import `hdstats` (with `module load dea` loaded), but get this error:

```
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /g/data/v10/public/modules/dea-env/20191127/lib/python3.6/site-packages/hdstats/geomedian.cpython-36m-x86_64-linux-gnu.so)
```

Others have found this too. It works fine on Gadi if you ssh, but not on the VDI. This possibly because they have different versions of glibc?

**Comment by robbibt** [comment]
Closed by changes for #260
