### ISSUE TITLE
Importing `hdstats` fails with "`GLIBC_2.14' not found" error on VDI

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/ga-datacube-env#260]
Importing the `hdstats` Python package fails on the VDI with the following error. This currently makes it impossible to compute geomedians on the VDI.

The `hdstats` package can be correctly imported on Gadi.

```
import hdstats

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-2afee298ff3e> in <module>
----> 1 import hdstats
/g/data/v10/public/modules/dea-env/20200612/lib/python3.6/site-packages/hdstats/__init__.py in <module>
      3 from .dists import Wishart, ChiSquared, MultivariateNormal, MarchenkoPastur
      4 
----> 5 from .geomedian import geomedian, nangeomedian
      6 
      7 # from .wishart import sample_wishart
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /g/data/v10/public/modules/dea-env/20200612/lib/python3.6/site-packages/hdstats/geomedian.cpython-36m-x86_64-linux-gnu.so)
```

**Comment by omad** [comment]
Hi @robbibt, thanks for reporting this. I've rebuilt `hdstats` as a _manylinux wheel_ and reinstalled it in the current environment module, which should make it work on both Gadi and VDI.

Can you please check and report back.

**Comment by robbibt** [comment]
Hey @omad , when I try to do a `import hdstats` I get this error on VDI and Gadi:

```
module use /g/data/v10/public/modules/modulefiles
module load dea
python3

>>> import hdstats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'hdstats'
```

I've shut down my notebook server and re-started, but it still appears.

**Comment by omad** [comment]
Oh dear, I really didn't make that better! 🤭 

It should be fixed now, and I've even tested it myself on Gadi and VDI since I'm not in a rush.

Let me know if you still have troubles. And sorry for the mess up.

**Comment by robbibt** [comment]
Haha, no problem at all - it's all working nicely on both the VDI and Gadi for me now. Will close the issue!

**Comment by wouellette** [comment]
Any chance of making the `hdstats` package a PyPI package? Or provide the extension as part of Dale Roberts' `hdmedians`?
