### ISSUE TITLE
Add string representation of CRS as a new metadata field in C3 products

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/ga-datacube-env#280]
It would be valuable for users to be able to query GA Collection 3 data by a dataset's native CRS. For example, this could be used as a filter to load only `EPSG:32656` data along a UTM boundary where both `EPSG:32655` and `EPSG:32656` CRSs exist (e.g. to ensure all data is loaded in native CRS with no resampling).

This could be resolved by:
-  Adding a new metadata field to GA Collection 3 products called `crs_raw` or `crs_str` that contains a string representation of the dataset's EPSG code (e.g.  `epsg:32656`). This would allow allow filtering based on native CRS when loading data using `dc.load`:

```
dc.load(product='ga_ls8c_ard_3',
        crs_str='epsg:32656',
        **query)
```

This would be required for the following GA Collection 3 products only (with the longer term aim to also include this metadata for Sentinel-2 too if those products are upgraded to become part of Collection 3 in the future):
- `ga_ls5t_ard_3` 
- `ga_ls7e_ard_3`
- `ga_ls8c_ard_3`
- `ga_ls_fc_3`
- `ga_ls_wo_3`

This change would also need to be implemented on both the NCI and Sandbox/AWS environments so that data can be loaded consistently across DEA environments.

**Comment by jeremyh** [comment]
- Added to the definitions in #281

- Deployed to NCI datacube:
```
❯ datacube metadata update digitalearthau/config/eo3/eo3*.odc-type.yaml
Updated "eo3_landsat_ard"
Updated "eo3_landsat_l1"
Updated "eo3"
❯ date
Thu Mar  4 14:56:09 AEDT 2021

❯ # Can we see it in the fields? Yes!
❯ datacube dataset search product=ga_ls8c_ard_3 --limit 1
id: 9781d762-6f48-4da5-b1a4-3657bb5abdfc
product: ga_ls8c_ard_3
status: active
locations:
- file:///g/data/xu18/ga/ga_ls8c_ard_3/106/068/2019/12/16/ga_ls8c_ard_3-2-0_106068_2019-12-16_final.odc-metadata.yaml
fields:
    cloud_cover: 9.841478561653918
    creation_time: 2021-02-22 06:16:16.113579+00:00
    crs_raw: epsg:32652
    dataset_maturity: final
... etc
```
---

@whatnick Who should we assign to run the same update on AWS+Sandbox datacubes?

**Comment by alexgleith** [comment]
Probably needed to have assigned me, @jeremyh!

**Comment by jeremyh** [comment]
Deployed by @omad to the AWS sandbox and dev databases.

Closing issue (reopen if you find problems)
