### ISSUE TITLE
Add Goal-Keeper responsibilities to the documentation

### ISSUE THREAD

**Issue by omad** [GeoscienceAustralia/ga-datacube-env#31]
We need somewhere to refer to for the responsibilities of the rotating goalkeeper role. It doesn't need a lot of detail, could simply be:

# Goal Keeper Responsibilities

## Level 1 Support
- Support requests on opendatacube Slack `#general` and `#develop` channels
- GitHub issues sent to digitalearthau or datacube-core

## Build manager
- Keep the CI loop green
  - Follow up with whoever broke it
  - Or simply fix it yourself

## Release manager
- Manage the release process, if a new release is required
- _Refer to documentation_

**Comment by smr547** [comment]
Happy to do this whilst I serve my time as the goalkeeper :-)

**Comment by smr547** [comment]
Release manager -- "Refer do documentation" -- Which documentation?

BTW: Work in progress under branch ``smr547-patch-1``

**Comment by andrewdhicks** [comment]
The DEA build docs are here:
http://datacube-core.readthedocs.io/en/stable/about/release_process.html

The ODC build docs are here:
http://geoscienceaustralia.github.io/digitalearthau/internal/release.html

**Comment by smr547** [comment]
Thanks Andrew.

Please review [draft document](https://github.com/GeoscienceAustralia/digitalearthau/blob/smr547-patch-1/docs/internal/goalkeeper_instructions.md)

**Comment by andrewdhicks** [comment]
Look good!

If we want to keep the page in markdown and have it appear on the http://geoscienceaustralia.github.io/digitalearthau site, we'll need to add Markdown support.

The instructions here: http://www.sphinx-doc.org/en/stable/markdown.html
will need to be applied to the docs build process here:
https://github.com/GeoscienceAustralia/digitalearthau/blob/smr547-patch-1/docs/deploy.sh#L19

**Comment by andrewdhicks** [comment]
Then you'll be able to add the page to the table of contents on this page:
https://github.com/GeoscienceAustralia/digitalearthau/blob/smr547-patch-1/docs/index.rst

**Comment by andrewdhicks** [comment]
Just a few things to fix up here, now that we have it rendered by sphinx:
* The **_Goal Keeper Responsibilities_** heading should be demoted in level, so it doesn't cause an extra entry in the ToC.
* The links in the **_Release Manager_** section aren't being rendered as links.

http://geoscienceaustralia.github.io/digitalearthau/internal/goalkeeper_instructions.html
