### ISSUE TITLE
Can't load modules from raijin

### ISSUE THREAD

**Issue by r-cassel** [GeoscienceAustralia/ga-datacube-env#74]
Hi

Data cube works fine from VDI

When I try to load any modules from raijin I get this message: 

> Attempting to create a new user for "username"...
> 
> An account for "username" already exists in the Data Cube Database, but
> we were unable to connect to it. This can happen if you have used the Data
> Cube from raijin, and are now trying to access from VDI, or vice-versa.
> 
> To fix this problem, please copy your ~/.pgpass file from the system you
> initially used to access the Data Cube, onto the current system.
> Please contact a datacube administrator to help resolve user account creation.
> 
I can locate the ~/.pgpass file on the VDI but I'm unsure where I need to copy it to

please help

cheers

**Comment by bellemae** [comment]
Hi Rebecca, 

The blue note at the bottom of the following doc page has the commands for this. http://geoscienceaustralia.github.io/digitalearthau/connect/nci_basics.html

**Comment by uchchwhash** [comment]
Seems like this was resolved!
