### ISSUE TITLE
Making modulespec.yaml-pip_cmd a little more generic

### ISSUE THREAD

**Issue by lpinner** [GeoscienceAustralia/ga-datacube-env#88]
I've been implementing the `build_environment_module.py some_module/modulespec.yaml` "way of doing things" for installing my QGIS plugin on the NCI  (when conda-forge package QGIS3).

One issue I've encountered is that [`build_environment_module.py`](https://github.com/GeoscienceAustralia/digitalearthau/blob/develop/modules/build_environment_module.py#L150) has the `--prefix` arg hardcoded in the install_pip_packages function.    

This is fine for a standard `pip` install, but while my plugin is technically a python package, it is not installed to a standard location (i.e. not site-packages et al.), instead it is copied to a directory not on the python path and the modulefile sets an env var (QGIS_PLUGINPATH) to tell QGIS where to load plugins from.  A pip command that works with this would be something like `pip install -v --no-deps **--target** {target} --compile --requirement {requirements} `.  

To accommodate this sort of pip install would you consider a PR to handle both target or prefix?

I was thinking of something along the lines of:

_some_module/modulespec.yaml_

    install_pip_packages:
      requirements: requirements.txt
      target: "{module_path}"
      pip_cmd: "module load my-env; pip "

_another_module/modulespec.yaml_

    install_pip_packages:
      requirements: requirements.txt
      prefix: "{module_path}"
      pip_cmd: "module load some-env; pip "

_build_environment_module.py_

    def install_pip_packages(pip_conf, variables):
        fill_templates_from_variables(pip_conf, variables)
        pip = pip_conf['pip_cmd']
        prefix = pip_conf.get('prefix')
        target = pip_conf.get('target')
        requirements = pip_conf['requirements']
        if prefix:
            dest = prefix
            arg =  f'--prefix {prefix}'
        else:
            dest = target
            arg =  f'--target {target}'
    
        LOG.debug(f'Installing pip packages from "{requirements}" into directory "{dest}"')
        run(f'{pip} install -v --no-deps {arg} --compile --requirement {requirements}')

**Comment by roarmstrong** [comment]
Seems reasonable to me. Any input @omad or @jeremyh ? My only thought is should we be checking explicitly whether target exists?

**Comment by omad** [comment]
Yeah, that sounds cool to me. Would definitely accept PR. :)

@roarmstrong Elsewhere I'm ensuring the target directory exists. For this case, I think `pip` might do that for us. Not 100% sure.

**Comment by lpinner** [comment]
@omad Yep, pip ensures target dir exists - https://github.com/pypa/pip/blob/master/src/pip/_internal/commands/install.py#L363
