### ISSUE TITLE
DEM manipulation

### ISSUE THREAD

**Issue by mjb-oz** [GeoscienceAustralia/ga-datacube-env#92]
Hi there,

Could pyDEM (https://pypi.python.org/pypi/pyDEM/0.1.1) be added to the DEA module.
It'd be useful for those of us who are using DEA along with some external data.
Currently I have to use ArcGIS or QGIS for this, so being able to generate the results as part of a bigger python workflow would be amazing.

Cheers guys, love your work!

**Comment by omad** [comment]
This has been added now.
